#!/bin/bash
# script will display all attached cards (active or not) with their corresponding ip, broadcast, and netmask

counter1=1
counter2=1

declare -a card
declare -a ip

ifconfig -a | grep -v "^ "| tr -s " " : | cut -d: -f1 > /root/first
while read text
do
card[$counter1]=$text
((counter1++))
done </root/first


ifconfig -a | egrep '.*\..*\..*\..*' | tr -s " " : | cut -d: -f4,5,6,7,8 > /root/second
while read text
do 
ip[$counter2]=$text
((counter2++))
done < /root/second

echo
echo -e "CardID \t\tIP           Broadcast          Netmask"
echo -e "______    ___________   _________________   _______________ "

echo
if [[ ${card[1]} == "lo" ]]; then
  echo ${ip[1]} > temporary
  ip=`cat temporary | cut -d: -f1`
  netmask=`cat temporary | cut -d: -f2,3`
  echo -e "${card[1]} \t  $ip \t\t\t  $netmask"
else
  echo -e "${card[1]} \t  ${ip[1]}" 
fi
 
echo
 
if [[ ${card[3]} == "lo" ]]; then
  echo ${ip[2]} > temporary
  ip=`cat temporary | cut -d: -f1`
  netmask=`cat temporary | cut -d: -f2,3`
  echo -e "${card[3]} \t  $ip \t\t\t  $netmask"
else
  echo -e "${card[3]} \t  ${ip[2]}" 
fi

echo

if [[ ${card[5]} == "lo" ]]; then
  echo ${ip[3]} > temporary
  ip=`cat temporary | cut -d: -f1`
  netmask=`cat temporary | cut -d: -f2,3`
  echo -e "${card[5]} \t  $ip \t\t\t  $netmask"
else 
  echo -e "${card[5]} \t  ${ip[3]}"
fi

echo

if [[ ${card[7]} == "lo" ]]; then
  echo ${ip[4]} > temporary
  ip=`cat temporary | cut -d: -f1`
  netmask=`cat temporary | cut -d: -f2,3`
  echo -e "${card[7]} \t  $ip \t\t\t  $netmask"
else 
  echo -e "${card[7]} \t  ${ip[4]}" 
fi




