#!/bin/bash

function GetData ()
{
read -p "Enter Sales Amount: " Sales
read -p "Enter Costs: " Costs
}

function ProfLoss ()
{
((Sales=$1))
((Costs=$2))
((Net=$Sales - $Costs))
if [[ $Net -eq 0 ]]
then
   echo "Profits and Losses are equal - Breakeven"
elif [[ $Net -gt 0 ]]
then
  echo "Profit of: " $Net
elif [[ $Net -lt 0 ]]
then
echo "Loss of: " $Net
fi
}

GetData
ProfLoss $Sales $Costs
