#!/bin/sh

awk -F: '{ print $7 ": " $0 }' | sort |
awk -F: '
{ if $1 == LastState 
                 print "\t" $2
                }

{if $1 != LastState 
                LastState = $1
                print $1
                print "\t" $2
          }'
