#!/bin/bash
# script to show how positional parameters are handled by a script
# uncomment the line that reads... set -xv ...to turn on debugging
# uncomment the last line that read... set +xv ... to turn off debugging
# after the script has completed
set -xv
echo "pos param 1 is equal to" $1
echo "pos param 2 is equal to" $2
echo "pos param 3 is equal to" $3
echo "pos param 4 is equal to" $4
echo "pos param 5 is equal to" $5
echo "pos param 6 is equal to" $6
(( num5=$5 ))
(( num6=$6 ))
echo $num5
echo $num6
set +xv
