#!/bin/bash
# show what happens when for loops are nested
#
echo "i  j  k"
echo "-------"
for ((i=1; i <= 4; i++))
do
    for ((j=1; j <= 3; j++))
    do
        for ((k=1; k <=6; k++))
        do
            ((count++))
            echo $i" " $j" " $k
        done
    done
done
((ii = $i - 1))
((jj = $j - 1))
((kk = $k - 1))
echo "The total number of iterations was: " $count
echo "That is because i was" $ii", j was" $jj", and k was" $kk "and" $ii "*" $jj "*" $kk "=" $count

