#!/bin/bash

function msg ()
{
dialog --msgbox "Exiting" 5 40
clear
}

dialog --fselect $HOME/bin/rha_add_student 5 50 2>$HOME/menu.$$

status=$?

if [[ $status -eq 0 ]]
then
filename=`cat $HOME/menu.$$`
echo "filename is $filename"

dialog --textbox $filename 15 70 

msg

rm $HOME/fs.$$

else

msg

fi


