#!/bin/bash
# script is used to populate the pwordfile used in the newuser/usernew 
# script to give a new user their original password. Use of the command
# passwd with the --stdin option allows for unattended password creation.
rm -fr /root/gecos
username=$1
read -p "First Name : " first
read -p "Last Name : " last
read -p "Enter Social Security Number with NO dashes: " socsec
echo $first:$last > /root/gecos
one=${first:0:2}
two=${last:0:3}
three=${socsec:5:4}
password=$one$two$three
echo "The password for $username is" $password
echo $password > /root/pwordfile
echo $last":"$first":"$password >> /root/usersadded
