#!/bin/bash
mkdir -p /root/test_bu
touch /root/test_bu/file.{1,2,3,4,5}.{org,com,edu,net}.{txt,jpg,dat}
mkdir -p /backup/archive
mv -i /backup/* /backup/archive
for ((i=1;i<3;i++))
do
   touch /root/test_bu/*.dat
   clear
   echo "backing up number $i data files..."
   sleep 5
   clear
   echo "backing up number $i data files......"
   sleep 5
   clear
   echo "backing up number $i data files........."
   sleep 5
   clear
   echo "backing up number $i data files............"
   sleep 5
   clear
   echo "backing up number $i data files..............."
   sleep 5
   clear
   echo "backing up number $i data files.................."
   sleep 5
   clear
   echo "backing up number $i data files....................."
   sleep 5
   clear
   echo "backing up number $i data files........................"
   sleep 5
   clear
   echo "backing up number $i data files..........................."
   sleep 5
   clear
   echo "backing up number $i data files.............................."
   sleep 5
   echo " backing up number $i data files................................"
   clear
   sleep 8
   echo "All number $i data files successfully backed up"
   sleep 2
   clear
   when=`date`
   mkdir -p /backup/"$i"bu"$when"
   cd /root
   find test_bu/*.dat -amin 1 >> captured
     while read text
     do
        cp -f $text /backup/"$i"bu"$when" 2>/dev/null
     done < captured
   rm captured
done
((num=$i-1)) 
echo "You successfully backed up $num data files!"
cd /backup
ls 
