#!/bin/bash 
# quickly convert html filenames for use on a dossy system
# only handles file extensions, not file names
clear
rm -fr /root/updated
rm -fr /html/*
mkdir /html/mine.html
mkdir /html/yours.html
touch /html/{1,2}{1,2,3,4,5,6,7,8,9}{1,2}.web.htm
touch /html/{1,2,3,4,5,6,7,8,9}{1,2,3,4,5,6,7,8,9}{1,2,3,4,5,6,7,8,9}.web.html
echo "The contents of the following directory needs to have all html extensions changed to htm for files but NOT directories,Also do not overwrite any files that already have .htm file extensions"
sleep 15
echo "Here is a look at the directory that needs to be updated."
sleep 2
ls /html | less
echo " The company needs this to happen in the next 30 minutes. Can you do it?"
sleep 3
echo "Here is my solution:"
read -p "Enter the directory you want to change all html FILE extensions to htm: " dir
cd $dir
for i in *.html; do
   if [ -f ${i%l} ]; then 
      echo "${i%l} already exists"
else 
     if [[ -f $i ]]; then
          mv $i ${i%l}
          echo "$i was renamed ${i%l}" >> /root/updated
 	echo"	check out /root/updated for info"

   fi
fi 
done 2>/dev/null
echo "Here is the new /html directory with the correct file extensions and directorys having .html extensions unchanged"
sleep 5 
ls /html
