#!/bin/bash

read -p "Enter your new password:  " pass
read -p "Re-enter your new password:  " pass1
if [[ $pass != $pass1 ]]
then
echo 'Passwords do not match! Please try again'
exit
fi
sudo echo $pass > /home/$USER/.password
sudo passwd --stdin $USER < /home/$USER/.password
rm /home/$USER/.password
updated=`date`
sudo echo $USER $pass $updated >> /root/users_and_passwords
#sudo cp /tmp/users_and_passwords /root/users_and_passwords
