#!/bin/bash
# script that will accept a persons first name last name and social security
# number and then use ${name:offset:length} (page 140) to set their password
# equal to first 2 of first, first 3 of last and last 4 of social security

read -p "First Name :" first
echo "first is equal to" $first
read -p "Last Name :" last
echo "last is equal to" $last
read -p "Social Security :" socsec
echo "socsec is equal to" $socsec
firstname="$first"
echo "firstname is equal to" $firstname
lastname="$last"
echo "lastname is equal to" $lastname
socialsecurity="$socsec"
echo "socialsecurity is equal to" $socialsecurity
a="${firstname:0:2}"
echo "a is equal to" $a
b="${lastname:0:3}"
echo "b is equal to" $b
c="${socialsecurity:5:4}"
echo "c is equal to" $c
password=$a$b$c
echo "Your new password is" $password
