#!/bin/bash
# This file runs a welcome screen and a menu choice of that wil let you view your current ENV settings.
clear
echo	Welcome $USER  
echo		to the "$HOSTNAME" system.
echo 		The current date and time is "$(date)" 	
echo 		To View current system runtime settings
echo		
echo
echo "1. Kernel Version"
echo "2. What shell"
echo "3  Terminal ID"
echo "4. Who is logged in"
echo "5. Current dir listing "
echo "6. Cat a File"
read -p "Please enter a selection: " ans 
echo " " 

case $ans in

1) cat /etc/issue | head -1 ;;
2) echo $SHELL |more ;;
3) tty |more ;;
4) who -a |more ;;
5) read -p "do you want a long listing? (Y or N)" yesno
        YN=`echo $yesno | tr [:lower:] [:upper:]`
        case $YN in
                Y) ls -al ;;
                *) ls ;;
        esac ;;
6) read -p "enter file name to view: " filename
        if [[ -a $filename ]]
        then
                cat $filename |more
        else
                echo "file does not exist"
        fi ;;

*) echo "invalid selection try again" ;;


esac
#sleep 5
echo " "
echo " " 
read -p "Do you wish to enter another selection? (yes or no): "  keepon
if [[ $keepon = "yes" ]]
then
/CIS239/extracredit/SHOW_ME_ENV_MENU               
else
exit
fi





