#!/bin/sh

awk -F: '{ print $2 ": " $0 }' | sort |
awk -F: '
$1 == "!!" {
                 print $2 > "user_no_password"  
                 
                }'

#$1 != LastState {
#                LastState = $1
#                print $1
#                print "\t" $2
#          }'
